version: '2'

services:
  nats:
    image: 'nats:latest'
    expose:
      - '4222'
    ports:
      - '4222:4222'
      - '8222:8222'
    hostname: nats
    # command: -DVV

  john:
    build:
      context: .
      dockerfile: ${PWD}/build/george/Dockerfile
    ports:
      - '4001:4001'
      # - '4222:4222'
